"""5

Revision ID: 640be2897d47
Revises: ded12dee40b6
Create Date: 2022-10-24 22:11:20.421992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640be2897d47'
down_revision = 'ded12dee40b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('title', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'title')
    # ### end Alembic commands ###
