"""third

Revision ID: 95ef026464b6
Revises: cadc01808d69
Create Date: 2022-10-20 10:55:13.987902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ef026464b6'
down_revision = 'cadc01808d69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
