"""third

Revision ID: a9e42a8c4e85
Revises: 95ef026464b6
Create Date: 2022-10-20 10:59:19.542736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e42a8c4e85'
down_revision = '95ef026464b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
