"""third

Revision ID: c19537a59233
Revises: a9e42a8c4e85
Create Date: 2022-10-20 11:03:38.039859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19537a59233'
down_revision = 'a9e42a8c4e85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
