"""first

Revision ID: cadc01808d69
Revises: ea0ca0cb4bd2
Create Date: 2022-10-18 20:25:23.568290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadc01808d69'
down_revision = 'ea0ca0cb4bd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
