"""4

Revision ID: ded12dee40b6
Revises: 02aeeb0e469d
Create Date: 2022-10-20 16:50:16.817251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded12dee40b6'
down_revision = '02aeeb0e469d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('change', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'change')
    # ### end Alembic commands ###
